# JEDEN DOCKERFILE DLA WSZYSTKIEGO
FROM node:22-alpine AS build

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .

# ✅ DODAJ ARGUMENTY DLA VITE
ARG VITE_GOOGLE_CLIENT_ID
ARG VITE_API_URL
ARG VITE_HOST
ARG DOCKER_ENV
ARG VITE_ALLOWED_HOSTS

# ✅ USTAW ZMIENNE ŚRODOWISKOWE
ENV VITE_GOOGLE_CLIENT_ID=$VITE_GOOGLE_CLIENT_ID
ENV VITE_API_URL=$VITE_API_URL
ENV VITE_HOST=$VITE_HOST
ENV DOCKER_ENV=$DOCKER_ENV
ENV VITE_ALLOWED_HOSTS=$VITE_ALLOWED_HOSTS

# ✅ LOGI
RUN echo "🔧 Building with VITE_API_URL: $VITE_API_URL"

# ✅ ZBUDUJ FRONTEND
RUN npm run build

# ✅ ZBUDUJ BACKEND (jeśli potrzebujesz)
RUN npx prisma generate

# ✅ ETAP PRODUKCYJNY - NGINX dla frontendu
FROM nginx:alpine

# ✅ SKOPIUJ FRONTEND
COPY --from=build /app/dist /usr/share/nginx/html

# ✅ SKOPIUJ KONFIGURACJĘ NGINX (jeśli masz)
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]