services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      no_cache: true
    ports:
      - "3000:3000"
    environment:
      PORT: ${PORT}
      JWT_SECRET: ${JWT_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      REACT_APP_API_URL: ${REACT_APP_API_URL}
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DATABASE_URL: ${DATABASE_URL}
      EWIDENCJA_DB_HOST: ${EWIDENCJA_DB_HOST}
      EWIDENCJA_DB_USER: ${EWIDENCJA_DB_USER}
      EWIDENCJA_DB_PASSWORD: ${EWIDENCJA_DB_PASSWORD}
      EWIDENCJA_DB_NAME: ${EWIDENCJA_DB_NAME}
      FREKWENCJA_DB_HOST: ${FREKWENCJA_DB_HOST}
      FREKWENCJA_DB_USER: ${FREKWENCJA_DB_USER}
      FREKWENCJA_DB_PASSWORD: ${FREKWENCJA_DB_PASSWORD}
      FREKWENCJA_DB_NAME: ${FREKWENCJA_DB_NAME}
      SM_DB_HOST: ${SM_DB_HOST}
      SM_DB_USER: ${SM_DB_USER}
      SM_DB_PASSWORD: ${SM_DB_PASSWORD}
      SM_DB_NAME: ${SM_DB_NAME}
      LOG_LEVEL: ${LOG_LEVEL}
      CONTRIBUTIONS_DB_HOST: ${CONTRIBUTIONS_DB_HOST}
      CONTRIBUTIONS_DB_USER: ${CONTRIBUTIONS_DB_USER}
      CONTRIBUTIONS_DB_PASSWORD: ${CONTRIBUTIONS_DB_PASSWORD}
      CONTRIBUTIONS_DB_NAME: ${CONTRIBUTIONS_DB_NAME}
      CONTRIBUTIONS_DB_PORT: ${CONTRIBUTIONS_DB_PORT}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
    restart: unless-stopped
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile # ← ZMIENIONE Z Dockerfile.backend na Dockerfile!
      args:
        - VITE_GOOGLE_CLIENT_ID=${VITE_GOOGLE_CLIENT_ID}
        - VITE_API_URL=http://panel.silamlodych.pl:3000
        - VITE_HOST=0.0.0.0
        - DOCKER_ENV=true
        - VITE_ALLOWED_HOSTS=turbine-protector-aluminum.ngrok-free.dev
    ports:
      - "8090:80"
    networks:
      - app-network
    depends_on:
      - backend
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
